### ISSUE TITLE
Feature request: handle tags

### ISSUE THREAD

**Issue by jlesquembre** [gbataille/gitHUD#10]
I started to use gitHUD a week ago and I find it really useful. Thanks for writing it!

But there is a feature I'm missing, when I checkout a tag, I see `[detached@c83f14e]`. Before I was using the default fishshell functionally to show git information, and in that case I had something like `(v1.0)`. What do you think about showing `[detached@v1.0]` when you checkout a tag?

**Comment by gbataille** [comment]
Hey José,

glad that you like it.

good idea. let me see what I can do

**Comment by gbataille** [comment]
Hey,

I just released 1.3.7 that should do what you wanted. Can you please try and let me know?

Cheers

**Comment by jlesquembre** [comment]
That was fast! I tried it and all looks good to me.

Thanks
