### ISSUE TITLE
Does gitHUD properly display the Dull colour intensity?

### ISSUE THREAD

**Issue by sheldond** [gbataille/gitHUD#13]
Hi Gregory! Thanks for building this fast alternative to git-radar! 😄 It's really helpful.

I have a question: I'm trying to configure some of the colours to be "Dull", but I'm not noticing any affect. It appears to me that gitHUD prints all colours as "Vivid", regardless of the config. Do you mind testing this on your end to see if you can reproduce it? I'm using zsh on macOS, I reproduced the issue on a minimal config. Please let me know what you think, thanks!

**Comment by gbataille** [comment]
Hey,

seems you are right, although I did not see it because with my terminal
config, most of my colours are the same in bright and dull.
I'll look into it

Thanks for reporting

**Comment by gbataille** [comment]
Hey @sheldond actually no, I get different outputs with different config.

![screen shot 2018-02-11 at 10 03 34](https://user-images.githubusercontent.com/1113065/36071685-e4ad7a74-0f12-11e8-9b42-2dfdd2545cfd.png)
![screen shot 2018-02-11 at 10 03 39](https://user-images.githubusercontent.com/1113065/36071682-e45d266e-0f12-11e8-94ac-24e8b220e6bd.png)
![screen shot 2018-02-11 at 10 03 51](https://user-images.githubusercontent.com/1113065/36071683-e47984bc-0f12-11e8-98f1-5dc7f74c5a16.png)
![screen shot 2018-02-11 at 10 03 54](https://user-images.githubusercontent.com/1113065/36071684-e494a436-0f12-11e8-85a8-921daa704d37.png)

I thought you were right because my Dull and Vivid colours are configured to be the same on almost all my colors, except Black and White. So a Red Dull and Red Vivid did appear the same, but that's because they are rendering the same way in my terminal. Could it be your issue too?

To test your terminal colour config, you can run:
```
for x in {0..1}; do for i in {30..37}; do echo -ne "\e[$x;$i""m\\\e[$x;$i""m\e[0;37;40m "; done; echo; done; echo ""
```

![screen shot 2018-02-11 at 10 07 03](https://user-images.githubusercontent.com/1113065/36071712-5d211f9c-0f13-11e8-8da3-b4a6036ae2ec.png)

**Comment by gbataille** [comment]
FYI, I intend to add support for 256 colors in the future if I have the motivation to work a bit rather than slack

**Comment by sheldond** [comment]
Hi @gbataille! I'm sorry for the very slow response on this, but I really appreciate your reply.

I think my terminal is okay (see screenshot, and thanks for the handy test script). But after looking at this more I think I've found that the issue may be that the one config option "local_branch_intensity" is not working (it's also possible I misinterpreted it). I should have done more testing before reporting, I think most of the other options are actually working fine for me! I'm just trying to make the entire githud "dull" but the branch still appears in "vivid".

Thanks again!

![screen shot 2018-02-12 at 11 04 43 am](https://user-images.githubusercontent.com/149429/36940195-6236bde4-1f0c-11e8-93aa-f1fd9e8b8261.png)

**Comment by gbataille** [comment]
Hey,

if you look at the example I gave, I did use this specific option `local_branch_intensity` and it was working, so I'm a bit surprised...

Can you maybe give me
* the prompt your are using
* your PS1 or PROMPT variable
* your .githudrc config file

**Comment by sheldond** [comment]
Hi @gbataille sorry again for the very slow reply, I've tried to use a minimal config, does this screenshot help you at all? 

![screen shot 2018-04-02 at 12 41 42 pm](https://user-images.githubusercontent.com/149429/38205093-494b0cd0-3673-11e8-92a2-45b0eb7781ad.png)

**Comment by sheldond** [comment]
Hi Gregory! Thanks!

When I use `local_branch_color=White` then the colour indeed changes from the default to white, but the intensity is still vivid.

I'm sorry the issue is persisting, I originally thought it might be very simple. At this point I feel like it's not worth your time for such a tiny detail... 🙂 But I do appreciate the attention you've already given it!

(Also sorry for the image, I realize it was hard to read, I thought you may have wanted to see the colours)

**Comment by gbataille** [comment]
ok, then I don't get it. This is working for me.

can you please do the following:

.githudrc
```
local_branch_color=White
local_branch_intensity=Dull
```

in a shell, in a folder that is a git repo:
```
githud zsh > dull.txt
```

This should contain
```
%{[39m%} [%{[37m%}master%{[39m%}] 1%{[1;37m%}A%{[39m%}
```
(don't use cat to see the content of the file as the special char will get interpreted, use vim for example)

Then
.githudrc
```
local_branch_color=White
local_branch_intensity=Vivid
```

in a shell, in a folder that is a git repo:
```
githud zsh > dull.txt
```
This should contain
```
%{[39m%} [%{[1;37m%}master%{[39m%}] 2%{[1;37m%}A%{[39m%}
```

The difference is the `1;` that prefixes the `37m` white color instruction for vivid. It's absent for dull. Are you getting this?

**Comment by sheldond** [comment]
Interesting thanks! Yes I'm seeing the exact same thing, when I set the config to Vivid then I see the `1;` prefix, when I set Dull then there is no prefix.

I think I know what's happening now: when the prefix is absent then the previously used prefix value is carried over. E.g. if the previous colour instruction was vivid then if the next colour instruction has no prefix it will also be vivid.

If I use `0;` for dull then it works regardless of previous values (as in the test code that you sent above). Does that make sense?

**Comment by gbataille** [comment]
ok so that's it because I'm not forcing the "non bold" state. But I expected to have it reset everytime. I'm not sure where it's getting the "bold" status from but I can reproduce now so I'll fix it one way or another

**Comment by gbataille** [comment]
ok, I was resetting the color but not the style. Odd that I had not picked it up before! release coming soon

**Comment by gbataille** [comment]
@sheldond 2.0.2 should be good now. Let me know

**Comment by sheldond** [comment]
@gbataille it's working! Perfect! Thanks again for taking care of this 😃
