### ISSUE TITLE
Change the name to githud

### ISSUE THREAD

**Issue by voidus** [gbataille/gitHUD#14]
It is a common convention that binaries have lower-case names. While gitHUD looks nice, some linux distros (namely arch) prohibit package names like gitHUD.

**Comment by gbataille** [comment]
yes I agree. It has been bugging me since the start actually. I'll try to work on that this week end.

thanks

**Comment by gbataille** [comment]
Hey @voidus, this is done.

I have published v2.0.0 with lowercase executable name.

Cheers
