### ISSUE TITLE
Doesn't display correctly inside of tmux

### ISSUE THREAD

**Issue by Thermatix** [gbataille/gitHUD#16]
So, I created a zsh script:

```zsh
#!/usr/local/bin/zsh -f
cd $1 && githud zsh
```

so I can then do this inside of tmux:

```
set -g pane-border-format '#{pane_current_command} #(~/.zsh/bin/githud_status "#{pane_current_path}")'
```
but it displays like this:
![alt with zsh](https://cdn.pbrd.co/images/Hy3nftt.png)

and even if I try it with `bash` or with nothing it shows like this:
![alt without zsh](https://cdn.pbrd.co/images/Hy3o1oc.png)

**Comment by gbataille** [comment]
Hey @Thermatix ,

Yes that makes complete sense. It's made only to be displayed inside a shell prompt, with the prompt escape characters. That's what the ZSH param is. It tells to use the ZSH Prompt escape characters.

I guess I could add an option to not "PROMPT-escape" the output.

I'll consider it (I'm a heavy user of tmux too and I find the way you want to use it interesting)

**Comment by Thermatix** [comment]
@gbataille thanks a lot!
Basically I'm tired of having my prompt cluttered with stuff so I'm doing an 'experiment' to see if it's viable to transfer most of this (and to add others) to the tmux pane status bar.
I like using githud because it's super fast compared to other git checkers.

It would be awesome if you just provided a tmux version, like with bash or zsh, i.e.`githud tmux` for portability, then you could make a config that would work no matter where you put it without having to a version that has `#[fg=red]` and a second version that has `Red`.

**Comment by gbataille** [comment]
Hey @Thermatix ,

I published 2.1.0 which should work for you. let me know

**Comment by Thermatix** [comment]
Awesome! it works, almost perfectly, as you can see here:

![tmux pane-boarder-format](https://cdn.pbrd.co/images/Hzg2oXM.png)

but it doesn't seem to acknowledge colours, despite me trying both, `"#[fg=<colour>]"` and simply `"<colour>"` in my `.githudrc`am I doing it wrong?

**Comment by gbataille** [comment]
you are not supposed to manually put color. The color of the elements is set through config and `githud` puts the right control characters.

What you are showing is that `githud tmux` puts `#[fg=default ]` everywhere, which is not the default...
Did you override the color config in the config file? what does it look like?

it's supposed to look like
```
# Colors are from [Black, Red, Green, Yellow, Blue, Magenta, Cyan, White, NoColor]
# NoColor is a special keyword to remove any specific color and use the 
# terminal foreground color
#
# Intensities are from [Vivid, Dull]
```
as written in the sample config file

Can you post your `.githudrc` if you can't figure it out?

**Comment by Thermatix** [comment]
It's ok, I think I know what the problem was,  no capitalized letters on colour names, I changed that using regex substitution to change all colours and boom, colours:

![pane status with colours!](https://cdn.pbrd.co/images/Hzh26N1.png)

only thing I would add is the ability to set colours for the numbers, other than that, perfection!

@gbataille thanks for your hard work!

**Comment by gbataille** [comment]
Cool.

Color for the numbers is not unreasonable. I'll create a separate issue for that.
