### ISSUE TITLE
brew install  `setup_ghc_compilers' 

### ISSUE THREAD

**Issue by alexmasselot** [gbataille/gitHUD#2]
>brew install githud
Error: undefined local variable or method `setup_ghc_compilers' for #<Class:0x007fbc0b085038>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/gbataille/homebrew-gba/Formula/githud.rb:15:in `<class:Githud>'
/usr/local/Library/Taps/gbataille/homebrew-gba/Formula/githud.rb:3:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:85:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:76:in `klass'
/usr/local/Library/Homebrew/formulary.rb:72:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/formulary.rb:352:in `find_with_priority'
/usr/local/Library/Homebrew/extend/ARGV.rb:20:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:45:in `install'
/usr/local/Library/brew.rb:143:in `<main>'

**Comment by alexmasselot** [comment]
after brew upgrade, the same errors is still on

brew --version
Homebrew 0.9.5 (git revision ff56; last commit 2016-01-05).

**Comment by gbataille** [comment]
Seems that the haskell helpers have changed

https://github.com/Homebrew/homebrew/commit/6cae57f4d0c778d6a3882cceacffa11af0c55cb9
https://github.com/Homebrew/homebrew/commit/fbbcaff7b62ecf6d0d9aaa3a64d7f3f8d5a6a2a0

I'll look into it soon

**Comment by gbataille** [comment]
Fixed by the new formula in homebrew-gba repo
