### ISSUE TITLE
brew install takes hours and hours

### ISSUE THREAD

**Issue by dfuentes77** [gbataille/gitHUD#25]
I left it overnight and it's still running.  I can compile my entire Gentoo operating systems in less time.  It's hard to promote this if `ghc` takes an absurd amount of time to compile.  

Is there an easier way of installing it?

I'm surprised there isn't a native precompiled (bottle) install via homebrew for macOS versions.

**Comment by gbataille** [comment]
wow, ok. Don't know why it would not try it without this option.

#21 is "just" a configuration issue.
Seems like the defaults I picked don't work everywhere (well that was kind of expected).
You'll have to change a bit the config in the `.githudrc` file that you can put in your `$HOME`

**Comment by gbataille** [comment]
Closing this as I never made any progress on it.
