### ISSUE TITLE
Make background color transparent or customizable

### ISSUE THREAD

**Issue by eproxus** [gbataille/gitHUD#7]
I'm migrating from [git-radar](https://github.com/michaeldfallen/git-radar) to gitHUD (while git-radar is no longer being maintained).

In my ZSH theme I have a colored bar where I like to put my Git status:
<img width="568" alt="screen shot 2016-08-15 at 10 12 03" src="https://cloud.githubusercontent.com/assets/112878/17659273/bc71880a-62d1-11e6-989f-1dec7137c6b1.png">

With gitHUD, the background seems to be hardcoded:
<img width="569" alt="screen shot 2016-08-15 at 10 20 35" src="https://cloud.githubusercontent.com/assets/112878/17659313/f22eef78-62d1-11e6-94f7-c135e03dee37.png">

I would love for it to be transparent or if that is not possible, customizable (also, there seems to be a trailing space after the last component).

**Comment by gbataille** [comment]
hey,
Let me have a look at this background thing, I'm not sure if I can make it
transparent, but if I can't I most certainly will be able to make it
configurable.
I'll look into making the trailing space configurable also.
Can't promise to be able to do that this week though :)
I'll keep you posted

**Comment by eproxus** [comment]
Thank you!

Regarding transparency, shouldn't setting foreground colors only achieve this and leave the rest to the terminal?

**Comment by gbataille** [comment]
I guess :)
I'll have a look, I did not realize I was setting a background !!!

**Comment by gbataille** [comment]
Hey so I think the issue is that to avoid side effects from people having colors opened at the start of the gitHUD prompt, I'm doing a reset of all the terminal attributes which I guess kills the background too.

There does not seem to be a reset of the foreground color only but there is a "default" foreground color. I'll try with that

**Comment by gbataille** [comment]
@eproxus I published a new version 1.3.4 which should fix both your issues.
Can you please let me know

**Comment by eproxus** [comment]
Brilliant, it looks perfect. Thanks for the quick turnaround time!
