### ISSUE TITLE
Install help for Haskell newbie

### ISSUE THREAD

**Issue by frederickjh** [gbataille/gitHUD#8]
Hi!
I have worked with a number of other programing languages, but Haskell is new to me. I tried the following on Ubuntu Linux 16.04 to install gitHUD:
```
sudo apt-get install cabal-install haskell-platform ghc
cabal update
cabal install gitHUD
```
This last command returns the following output:
```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: gitHUD-1.3.5
rejecting: base-4.6.0.1/installed-8aa... (conflict: gitHUD => base>=4.7 && <5)
rejecting: base-4.9.1.0, 4.9.0.0, 4.8.2.0, 4.8.1.0, 4.8.0.0, 4.7.0.2, 4.7.0.1,
4.7.0.0, 4.6.0.1, 4.6.0.0, 4.5.1.0, 4.5.0.0, 4.4.1.0, 4.4.0.0, 4.3.1.0,
4.3.0.0, 4.2.0.2, 4.2.0.1, 4.2.0.0, 4.1.0.0, 4.0.0.0, 3.0.3.2, 3.0.3.1 (global
constraint requires installed instance)
```
Compiler version is:
```
haskell-compiler --version
The Glorious Glasgow Haskell Compilation System, version 7.6.3
```
I see it is a dependency issue but I am not sure what to do to resolve this issue. I thought that cabal was a dependency manager but maybe it is not.  A point in the correct direction would be appreciated.
Thanks in advance for any help you can provide!
Frederick

**Comment by gbataille** [comment]
Hello Frederick,

It seems that you have pulled version 7.6 of GHC (haskell compiler), which
judging by the message you get, pulls in version 4.6 of the "standard
library" base, while I expect 4.7 or more. I don't know if there is a good
reason for that. I just used the dependencies available at the time when I
wrote the tool

I just tried on brand new ubuntu 16 vm and it works like a charm, but it
pulled me ghc 7.10, not 7.6
Actually you only need to install cabal-install. It'll pull the necessary
deps (ghc) on its own. I think haskell-platform is not necessary and might
even be causing version issues (that might be your problem)
Can you try to do


> sudo apt remove cabal-install haskell-platform ghc

sudo apt update
> sudo apt install --upgrade cabal-install

**Comment by gbataille** [comment]
Frederick, were you able to make it work?

**Comment by frederickjh** [comment]
Sorry, I did not get back sooner. I realized that i was on Ubuntu 14.04. 

 I tried what you said but I am still getting 7.6.
<pre>$ sudo apt install --upgrade cabal-install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  alex freeglut3-dev happy libxmu-dev libxmu-headers
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  ghc
Suggested packages:
  ghc-prof ghc-doc haskell-doc llvm
The following NEW packages will be installed:
  cabal-install ghc
0 upgraded, 2 newly installed, 0 to remove and 52 not upgraded.
Need to get 28.0 MB of archives.
After this operation, 302 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ubuntu.ethz.ch/ubuntu/ trusty/universe cabal-install amd64 1.16.0.2-2 [2,017 kB]
Get:2 http://ubuntu.ethz.ch/ubuntu/ trusty/universe ghc amd64 7.6.3-10 [26.0 MB]
Fetched 28.0 MB in 8s (3,155 kB/s)                                             
Selecting previously unselected package cabal-install.
(Reading database ... 514915 files and directories currently installed.)
Preparing to unpack .../cabal-install_1.16.0.2-2_amd64.deb ...
Unpacking cabal-install (1.16.0.2-2) ...
Selecting previously unselected package ghc.
Preparing to unpack .../ghc_7.6.3-10_amd64.deb ...
Unpacking ghc (7.6.3-10) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up cabal-install (1.16.0.2-2) ...
Setting up ghc (7.6.3-10) ...
update-alternatives: using /usr/bin/runghc to provide /usr/bin/runhaskell (runhaskell) in auto mode
update-alternatives: using /usr/bin/ghc to provide /usr/bin/haskell-compiler (haskell-compiler) in auto mode</pre>

At this point even though I think the speed over a git-radar shell script would be nice, I am stuck without dependency.

I am currently using my own git prompt that I found somewhere add modified.
Thanks again for your time and help!
Frederick

**Comment by gbataille** [comment]
I'll try to find some time to spin up a VM on ubuntu 14 then.
I'm quite sure it will compile

if you have time, you can always try to
- clone the repo
- edit githud.cabal and change "base >= 4.7" to "base >= 4.6"
- run "stack install" from the base of the repo

if it compiles fine, gitHUD will then be installed in something like
~/.local/... (exact path will be outputed in the prompt)

**Comment by gbataille** [comment]
I just did it on a VM and it worked
---

ok so there is no deb package to install `stack` on ubuntu 14. you need to do 
```
wget -qO- https://get.haskellstack.org/ | sh
```
then clone the repo
```
git clone https://github.com/gbataille/gitHUD.git
```
You actually need to tell stack to fetch a ghc that is better than the one ubuntu 14 packs (if you are familiar with rvm for ruby, nvm for node or virtualenv for python, stack does the same kind of things for haskell)
```
stack setup
```
then run "stack install" from the base of the repo
```
stack install
```
